apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-model-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-model-api
  template:
    metadata:
      labels:
        app: iris-model-api
    spec:
      containers:
        - name: iris-model-api
          imagePullPolicy: Always
          image: pedrocwb/ml-iris-model-rmq:latest
          ports:
            - containerPort: 80
          env:
            - name: RMQ_HOSTs
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-cluster-default-user
                  key: host
            - name: RMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-cluster-default-user
                  key: username
            - name: RMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-cluster-default-user
                  key: password
          resources:
            limits:
              cpu: 128m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 100Mi
---

apiVersion: v1
kind: Service
metadata:
  name: iris-model-service
spec:
  selector:
    app: iris-model-api
  ports:
    - name: http
      port: 8001
      targetPort: 80
  type: LoadBalancer

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: iris-model-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iris-model-api
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80